const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),store=require('./orderStore');
const PORT=Number(process.env.PORT||3000),ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'admin123',sessions=new Set();
function send(res,c,b,h={}){res.writeHead(c,h);res.end(b)}function json(res,c,d){send(res,c,JSON.stringify(d),{'Content-Type':'application/json; charset=utf-8'})}
async function read(req){let b='';for await(const c of req)b+=c;try{return JSON.parse(b||'{}')}catch{return {}}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x[0]))}
function isAdmin(req){const sid=cookies(req).sid;return sid&&sessions.has(sid)}function need(req,res){if(!isAdmin(req)){json(res,401,{error:'NOT_LOGGED_IN'});return false}return true}
function serve(req,res){let p=new URL(req.url,'http://x').pathname;if(p==='/')p='/index.html';if(p==='/admin')p='/admin.html';const f=path.join(__dirname,'public',p),base=path.join(__dirname,'public');if(!f.startsWith(base))return send(res,403,'Forbidden');if(!fs.existsSync(f))return send(res,404,'Not found');const t={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'}[path.extname(f)]||'application/octet-stream';send(res,200,fs.readFileSync(f),{'Content-Type':t})}
http.createServer(async(req,res)=>{const url=new URL(req.url,'http://x');try{
if(url.pathname==='/api/admin/login'&&req.method==='POST'){const b=await read(req);if(b.password!==ADMIN_PASSWORD)return json(res,403,{error:'Sai mật khẩu'});const sid=crypto.randomBytes(24).toString('hex');sessions.add(sid);return send(res,200,JSON.stringify({ok:true}),{'Content-Type':'application/json; charset=utf-8','Set-Cookie':`sid=${sid}; HttpOnly; Path=/; SameSite=Lax; Max-Age=86400`})}
if(url.pathname==='/api/admin/logout'){const sid=cookies(req).sid;if(sid)sessions.delete(sid);return send(res,200,JSON.stringify({ok:true}),{'Content-Type':'application/json; charset=utf-8','Set-Cookie':'sid=; HttpOnly; Path=/; Max-Age=0'})}
if(url.pathname==='/api/admin/me'){if(!need(req,res))return;return json(res,200,{ok:true,name:'Admin'})}
if(url.pathname==='/api/order'&&req.method==='POST'){const b=await read(req);const o=store.createOrder({customerName:b.customerName,discord:b.discord,service:b.service,packageName:b.packageName,price:b.price,payment:b.payment,login:b.login||{}});return json(res,200,{ok:true,orderId:o.id})}
if(url.pathname==='/api/track'){const o=store.getOrder(url.searchParams.get('id'));if(!o)return json(res,404,{error:'ORDER_NOT_FOUND'});return json(res,200,{id:o.id,service:o.service,packageName:o.packageName,price:o.price,status:o.status,createdAt:o.createdAt,logs:(o.logs||[]).map(l=>({type:l.type,message:l.message,createdAt:l.createdAt}))})}
if(url.pathname==='/api/orders'&&req.method==='GET'){if(!need(req,res))return;return json(res,200,{orders:store.listOrders()})}
let m=url.pathname.match(/^\/api\/orders\/([^/]+)\/status$/);if(m&&req.method==='PATCH'){if(!need(req,res))return;const b=await read(req);const o=store.updateStatus(m[1],b.status,'admin');return o?json(res,200,{order:o}):json(res,404,{error:'ORDER_NOT_FOUND'})}
m=url.pathname.match(/^\/api\/orders\/([^/]+)\/log$/);if(m&&req.method==='POST'){if(!need(req,res))return;const b=await read(req);const o=store.addLog(m[1],b.type||'note',b.message||'','admin');return o?json(res,200,{order:o}):json(res,404,{error:'ORDER_NOT_FOUND'})}
m=url.pathname.match(/^\/api\/orders\/([^/]+)\/note$/);if(m&&req.method==='PATCH'){if(!need(req,res))return;const b=await read(req);const o=store.saveStaffNote(m[1],b.staffNote||'','admin');return o?json(res,200,{order:o}):json(res,404,{error:'ORDER_NOT_FOUND'})}
m=url.pathname.match(/^\/api\/orders\/([^/]+)\/clear-login$/);if(m&&req.method==='POST'){if(!need(req,res))return;const o=store.clearLogin(m[1],'admin');return o?json(res,200,{order:o}):json(res,404,{error:'ORDER_NOT_FOUND'})}
return serve(req,res)}catch(e){console.error(e);return json(res,500,{error:'SERVER_ERROR',message:e.message})}}).listen(PORT,()=>console.log(`Atlantis web-only: http://localhost:${PORT}`));
